In [9]:
import pickle
import pandas as pd

In [10]:
pd.read_csv('hold_out_features.csv')

,Unnamed: 0,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,0,6320,240000,1,1,1,44,-1,-1,-1,...,2701,2427,1104,2362,2188,2701,2427,1104,2362,519
1,1,29659,50000,1,3,1,41,0,0,0,...,48468,39203,28913,26636,1816,1753,1433,990,967,1071
2,2,28347,20000,2,3,1,41,0,0,0,...,11583,13079,14546,16149,2000,1600,2000,2000,2000,2000
3,3,8523,320000,2,1,2,34,-2,-2,-2,...,-528,-1336,-1336,-1336,0,4,0,0,0,0
4,4,22135,120000,2,2,1,23,0,0,0,...,66825,68820,69776,71297,3000,2500,3100,2700,2800,2800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5996,5996,15903,200000,2,1,2,30,-1,-1,2,...,75635,94454,60875,41221,15349,10,32000,0,3000,0
5997,5997,23088,100000,2,2,1,36,2,2,2,...,77977,79071,76918,81713,3500,3300,3000,0,6500,3000
5998,5998,20147,50000,2,2,1,42,3,3,2,...,24574,24348,16130,16467,500,1200,516,566,585,608
5999,5999,19284,70000,2,1,1,32,0,0,0,...,71314,71595,70040,68927,2900,2766,3648,2700,2487,2600
6000,6000,20567,80000,1,2,2,29,2,0,0,...,13150,13233,13663,13994,2000,2200,600,650,700,1449

In [3]:
model_pickle_path = 'best_forest_model.pkl'
forest_file = open(model_pickle_path, 'rb')
forest = pickle.load(forest_file)
print("Loaded XGboost model :: ", forest_file)

Loaded XGboost model ::  <_io.BufferedReader name='best_forest_model.pkl'>

In [5]:
def pickle_read(path):
    with open(path, "rb") as f:
        pickle_file = pickle.load(f)
    return pickle_file
test_file = pickle_read("best_forest_model.pkl")

In [7]:
test_file

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=5, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [11]:
holdout = pd.read_csv("hold_out_features.csv")
holdout.rename(columns={"PAY_0":"PAY_1"}, inplace=True)
holdout= credit_functions.replace_unknowns(holdout)
holdout=credit_functions.calculate_utilization(holdout)
final_X=holdout[selection]
scaler.transform(final_X)
final_y = forest.predict(final_X)
pd.Series(final_y).to_csv("predictions.csv", index=False)

NameError: name 'credit_functions' is not defined